// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['editor']['Editor']['Greet'](arg1);
}

export function OpenProjectDialog() {
  return window['go']['editor']['Editor']['OpenProjectDialog']();
}

export function Weezafoo(arg1) {
  return window['go']['editor']['Editor']['Weezafoo'](arg1);
}
